---
apiVersion: v1
kind: ConfigMap
metadata:
  name: capvcd-1.25.6-d2iq-defaults
  namespace: ${releaseNamespace}
data:
  values.yaml: |-
    ---
    vcd:
      site: https://192.168.140.181
      org: d2iq
      org_vdc: Oscorp-Workload
      org_vdc_network: Oscorp-Workload-Network
    cluster:
      cni: antrea
      ccm: external
      csi: external
      kubernetesVersion: v1.25.6
      catalog: dkp
      vAppTemplate: dkp-2.4.0-airgapped-ubuntu-k8s-v1.25.6
      kubernetes_pv_storageProfile: vSAN Default Storage Policy
      cidr:
        pod: 99.96.0.0/11
        service: 99.64.0.0/13
      #k8s_svc_vip_range: 10.39.0.57-10.39.0.60 # Required  
      isManagement: false
      http_proxy: null
      https_proxy: null
      no_proxy: null
      refresh_token_b64: null
      capv_credentials_secret: null
      encryptionConfigValueB64: a2luZDogRW5jcnlwdGlvbkNvbmZpZwphcGlWZXJzaW9uOiB2MQpyZXNvdXJjZXM6CiAgLSByZXNvdXJjZXM6CiAgICAgIC0gc2VjcmV0cwogICAgICAtIGNvbmZpZ21hcHMKICAgIHByb3ZpZGVyczoKICAgICAgLSBhZXNjYmM6CiAgICAgICAgICBrZXlzOgogICAgICAgICAgICAtIG5hbWU6IGtleQogICAgICAgICAgICAgIHNlY3JldDogYW5BU2pDYk9JMFcxT3NJbHdpS1FKWHRHT2JQR0dkWHprMGpGYkNSRjNKbz0KICAgICAgLSBpZGVudGl0eToge30=
    controlplane:
      vip_interface: ens160
      #vip_ip: 10.39.0.56
      ssh_key:
      replicas: 3
      poolClass: standard